version: "3"
services:
  student_service:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo-studentdb-service/student_db
    ports:
      - "8080:8080"

  mongo:
    restart: unless-stopped
    image: mongo:4
    ports:  - "27017:27017"
